### ISSUE TITLE
(node) sys is deprecated. Use util instead.

### ISSUE THREAD

**Issue by Splaktar** [benlowry/node-geoip-native#8]
Line 136 `var sys = require("sys");` needs to be `var sys = require("util");`.

**Comment by gavinaiken** [comment]
@benlowry are you still maintaining this package? I can submit a pull request for this issue if you like, would be nice to get it fixed. I don't think the `sys` or `util` modules are even needed in the script so the PR can simply delete line 136.

**Comment by benlowry** [comment]
Hi @gavinaiken, I've very belatedly sorted this for you.

**Comment by Splaktar** [comment]
Thanks for fixing this in 6f2ff9dd02c583dc6c834ae679bd0fb2e2e5dfc5.
